### ISSUE TITLE
token_auth in Reports page widgets screws up some users

### ISSUE THREAD

**Issue by bondjimbond** [DiegoPino/islandora_piwik#14]
See my issue and possible solution on the Piwik project here: https://github.com/piwik/piwik/issues/11527

Including a token_auth in the widget URL in the Reports page forces users to "log in" to see data, even when already logged in and/or have appropriate permissions in both Drupal and Piwik.

According to https://github.com/piwik/piwik/issues/11527 removing the token_auth from the widget URL solves the problem.

**Comment by mjordan** [comment]
@bondjimbond I'm embarked to admit that I've lost focus on this module. I'd welcome a pull request to remove the widget, if you're willing to open one.

That said, I do need to implement this here at SFU in the short term so will be returning to it soon. I'd love to hear your specific use cases to be sure that they are accounted for.

**Comment by bondjimbond** [comment]
Removing the piece "&token_auth=$token_auth" from each URL in islandora_piwik.module does the job if you're allowing anonymous users to view the site, but redirects to a login if you aren't.

I'm beginning to suspect that Karen might have just put in the wrong value in that field; checking with her.

**Comment by bondjimbond** [comment]
Looks like she missed a few characters from her API key. Never mind - this is working as intended. 

Sigh.

**Comment by mjordan** [comment]
No problem, but I still need to give this module some TLC.
