### ISSUE TITLE
How should we handle nested collections?

### ISSUE THREAD

**Issue by mjordan** [DiegoPino/islandora_piwik#17]
Currently, collection usage is tracked at the immediate parent collection only, i.e., if an object is viewed, its parent collection is also "used". But how should we count grandparent and other far-ancestor collections? Maybe allow an option that if ancestors are indexed in Solr, loop through them and record a use for each one? Or keep it as is, counting immediate parent collections only?

**Comment by bondjimbond** [comment]
Counting earlier ancestors than parent collections is probably an overcomplication. How far back would it go? Does that mean every interaction counts as a hit for islandora:root? Immediate collection relationships should be fine... Folks who want to do more with it can do the math afterward, no?

**Comment by mjordan** [comment]
I agree, thanks for the confirmation. I'll close this. If the question comes up again, we can reopen.
