### ISSUE TITLE
Undefined Offset error when viewing objects with no parent collection

### ISSUE THREAD

**Issue by bondjimbond** [DiegoPino/islandora_piwik#19]
This happens when viewing a Newspaper Page object; I believe it's because these pages are not in any Collections.

> Notice: Undefined offset: 0 in islandora_piwik_get_ancestor_collections() (line 255 of /var/www/drupal7/sites/all/modules/islandora_piwik/islandora_piwik.module).

**Comment by mjordan** [comment]
Would you be able to open a PR to fix this? Wrapping that line 255 in an `if (count($results)) {} check might be enough.

**Comment by DiegoPino** [comment]
Resolved via https://github.com/DiegoPino/islandora_piwik/issues/19
